apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sports-league.fullname" . }}-backend-config
  labels:
    {{- include "sports-league.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  MONGODB_URI: {{ if .Values.mongodb.enabled }}mongodb://{{ include "sports-league.fullname" . }}-mongodb:27017/sports-league{{ else }}mongodb://mongodb-service:27017/sports-league{{ end }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  JWT_EXPIRE: {{ .Values.config.jwtExpire | quote }}
