{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sports-league.fullname" . }}-mongodb
  labels:
    {{- include "sports-league.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sports-league.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "sports-league.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_DATABASE
              value: "sports-league"
          {{- if .Values.mongodb.persistence.enabled }}
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
      {{- if .Values.mongodb.persistence.enabled }}
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: {{ include "sports-league.fullname" . }}-mongodb-pvc
      {{- else }}
      volumes:
        - name: mongodb-storage
          emptyDir: {}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sports-league.fullname" . }}-mongodb
  labels:
    {{- include "sports-league.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "sports-league.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
