# Default values for open-league
replicaCount: 2

image:
  repository: "open-league-"
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  backendPort: 3001

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: open-league.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  frontend:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  backend:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

mongodb:
  enabled: true
  image:
    repository: mongo
    tag: "7.0"
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    size: 8Gi
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

config:
  nodeEnv: "production"
  port: 3001
  jwtSecret: "your-super-secret-jwt-key-change-this-in-production"
  jwtExpire: "7d"
