apiVersion: v1
kind: ConfigMap
metadata:
  name: sports-league-backend-config
  namespace: default
data:
  NODE_ENV: "production"
  PORT: "3001"
  MONGODB_URI: "mongodb://mongodb-service:27017/sports-league"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  JWT_EXPIRE: "7d"
